version: '3.3'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"  # Admin UI
      - "443:443"
    volumes:
      - config:/app/config/production.json
      - data:/data
      - letsencrypt:/etc/letsencrypt

  wekan-db:
    image: mongo:4.2
    container_name: wekan-db
    volumes:
      - db-data:/data/db  # Named volume for database data

  wekan:
    image: wekanteam/wekan:latest
    container_name: wekan
    environment:
      - MONGO_URL=mongodb://wekan-db:27017/wekan
      - ROOT_URL=http://wekan.localhost
    depends_on:
      - wekan-db

volumes:
  config:        # Named volume for Nginx Proxy Manager config
  data:          # Named volume for Nginx Proxy Manager data
  letsencrypt:   # Named volume for SSL certificates
  db-data:       # Named volume for Wekan database data

networks:
  default:
    external:
      name: nginx-proxy
