version: '3.3'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"  # Admin UI
      - "443:443"
    volumes:
      - config:/config
      - data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - web-network

  wekan-db:
    image: mongo:4.2
    container_name: wekan-db
    volumes:
      - db-data:/data/db
    networks:
      - db-network

  wekan:
    image: wekanteam/wekan:latest
    container_name: wekan
    environment:
      - MONGO_URL=mongodb://wekan-db:27017/wekan
      - ROOT_URL=http://YOURFQDN
    depends_on:
      - wekan-db
    networks:
      - web-network
      - db-network
    ports:
      - 5000:8080

volumes:
  data:           # Nginx Proxy Manager data
  config:         # Proxy Manager config
  letsencrypt:    # SSL certificates
  db-data:        # Wekan database data

networks:
  web-network:
    driver: bridge
  db-network:
    driver: bridge
