version: '3.3'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - web-network
    environment:
      - ACME_AGREE=true  # Agree to Let's Encrypt Subscriber Agreement

  wekan-db:
    image: mongo:4.2
    container_name: wekan-db
    volumes:
      - db-data:/data/db
    networks:
      - db-network

  wekan:
    image: wekanteam/wekan:latest
    container_name: wekan
    environment:
      - MONGO_URL=mongodb://wekan-db:27017/wekan
      - ROOT_URL=https://FQDN
      # - MAIL_URL=smtp://user:pass@smtpserver.example.com:25/
    depends_on:
      - wekan-db
    networks:
      - web-network
      - db-network
    ports:
      - 5000:8080

volumes:
  caddy_config:   # Caddy configuration
  caddy_data:     # Caddy data
  db-data:        # Wekan database data

networks:
  web-network:
    driver: bridge
  db-network:
    driver: bridge
